name: "action-Releases-log"
description: "Automatically generating published logs is suitable for simple projects"
author: "duolabmeng6"
inputs:
  GITHUB_TOKEN:
    description: "secrets.GITHUB_TOKEN"
    default: "GITHUB_TOKEN"
  releasesText:
    description: "releasesText"
    default: "{{最新发布信息}}\n{{变更内容}}"
outputs:
  Body:
    description: "Body"
runs:
  using: "docker"
  image: "Dockerfile"